routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\OrderController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Client\CartController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/product', [HomeController::class, 'products'])->name('productlist');

Route::get('/index', function () {
    return view('client.layout.app');
});

Route::get('/blog', function () {
    return view('client.blog.blog');
})->name('blog');

Route::get('/myaccount', function () {
    return view('client.myaccount.dashboard');
})->name('myaccount');

Route::get('/client_account', function () {
    return view('client.myaccount.account');
})->name('myaccount');

Route::get('/client_address', function () {
    return view('client.myaccount.addresses');
})->name('myaccount');

Route::get('/client_wishlist', function () {
    return view('client.myaccount.wishlist');
})->name('myaccount');

Route::get('/client_orders', function () {
    return view('client.myaccount.orders');
})->name('myaccount');

Route::get('/about', function () {
    return view('client.about.about');
})->name('about');

Route::get('/contact', function () {
    return view('client.contact.contact');
})->name('contact');

Route::get('/productdetail', function () {
    return view('client.product.productdetail');
})->name('productdetail');

Route::get('/myaccount/orders', [MyAccountController::class, 'orders'])->name('myaccount.orders');

Route::prefix('admin')->group(function () {
    Route::get('/categories', [CategoryController::class, 'index'])->name('admin.categories.index');
    Route::get('/categories/create', [CategoryController::class, 'create'])->name('admin.categories.create');
    Route::post('/categories', [CategoryController::class, 'store'])->name('admin.categories.store');
});

Route::get('product/{category_id}', [ClientProductController::class, 'index']) -> name('client.product.productlist');

Route::get('productdetail/{id}', [ClientProductController::class, 'show']) -> name('client.product.productdetail');


//admin route
Route::middleware('auth')->group(function(){
 
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard');

    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('products', ProductController::class);
    Route::resource('coupon', CouponController::class);
    Route::post('/admin/products', [AdminController::class, 'products'])->name('admin.products');

});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/search', [ClientProductController::class, 'search'])->name('client.product.search');

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class, 'store']) -> name('client.cart.add');
    Route::get('cart', [CartController::class, 'index']) -> name('client.cart.cart');
    Route::post('update-quantity-product-in-cart/{cart_product_id}', [CartController::class, 'updateQuantityProduct'])->name('client.cart.update_product_quantity');

    Route::post('apply-coupon', [CartController::class, 'applyCoupon']) ->name('client.cart.apply_coupon');
    Route::get('checkout', [CartController::class, 'checkout']) -> name('client.checkout.index')->middleware('user.can_checkout_cart');
    Route::post('process-checkout', [CartController::class, 'processCheckout'])->name('client.checkout.proccess')->middleware('user.can_checkout_cart');

});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    use HasFactory;

    protected $fillable = [
        'name',
        'display_name',
        'group',
        'guard_name',
    ] ;
    public function permisions(): HasManyThrough
    {
        return $this->hasManyThrough(Permission::class, RoleHasPermissions::class,'role_id','id',"id","permission_id");
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Roles\UpdateRoleRequest;
use App\Models\Permisson;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $roles = Role::latest('id')->paginate(3);
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $permissions = Permisson::all()->groupBy('group');
        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    private function createPermission($request,$role){
        foreach($role->permisions as $permission){
            DB::table('role_has_permissions')->where('permission_id', $permission->id)->where("role_id",$role->id)->delete();
        }
        // $role->permissions()->sync($dataUpdate['permission_ids']);
        foreach(Permission::all() as $permission){
            if(isset($request["permission_ids_".$permission->id]))
                DB::table("role_has_permissions")->insert([
                    "permission_id"=>$permission->id,
                    "role_id"=>$role->id
                ]);
        }
    }
    public function store(Request $request)
    {
        //
        $dataCreate = $request->all();
        $dataCreate['guard_name'] = 'web';
        $role = Role::create($dataCreate);
        self::createPermission($request, $role);
        return to_route('roles.index')->with(['message' =>'create success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $role = Role::with('permissions')->findOrFail($id);
        $permissions = Permisson::all()->groupBy('group');
        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, $id)
    {
        //
        $role = Role::findOrFail($id);
        $dataUpdate = $request->all();
        $role->update($dataUpdate);
        self::createPermission($request, $role);
        return to_route('roles.index')->with(['message'=> 'edit success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Role::destroy($id);
        return to_route('roles.index')->with(['message'=> 'delete success']);
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layout.app')
@section('title', 'Create Roles')
@section('content')
    <div class="card">
    
        <h1>Create role</h1>
        
        <div>
            <form action="{{ route('roles.store') }}" method="post">
                @csrf
                <div class="modal-body px-4">

                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            </div>
                            @error('name')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror

                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="lastName">Display Name</label>
                                <input type="text" class="form-control" name="display_name" value="{{ old('display_name') }}">
                            </div>
                            @error('display_name')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <label name="group" class="ms-4">Group</label>
                            <select name="group" class="form-control">
                                <option value="system">System</option>
                                <option value="user">User</option>

                            </select>

                            @error('group')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>

                        <div class="row form-group">
                            <label for="Permission">Permission</label>
                            @foreach ($permissions as $groupName => $permission)
                            <div class="col-lg-4">
                                <label for="">{{ $groupName }}</label>
                                <div class="form-group">
                                    @foreach ($permission as $item)
                                    <div class="form-check"> 
                                            <input type="checkbox" class="form-check-input" name="permission_ids_{{$item->id}}" value="{{ $item->id }}">
                                            <label class="custom-control-label" for="">{{ $item->display_name }}</label>
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>

                <div class="modal-footer px-4">
                    <a href="{{ route('roles.index')}}"><button type="button" class="btn btn-secondary btn-pill">Cancel</button></a>
                    <button type="Submit" class="btn btn-submit btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layout.app')
@section('title', 'Edit Roles ' . $role->name)
@section('content')
<div class="card">
        
        <h1>Edit role</h1>

        <div>
            <form action="{{ route('roles.update', $role->id) }}" method="post">
                @csrf
                @method('PUT')


                <div class="modal-body px-4">
                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') ?? $role->name }}">
                            </div>
                            @error('name')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Display Name</label>
                                <input type="text"class="form-control" name="display_name"
                                value="{{ old('display_name') ?? $role->display_name }}">
                            </div>
                                @error('display_name')
                                    <span class="text-danger"> {{ $message }}</span>
                                @enderror
                        </div>

                        <div class="col-lg-6">
                            <label name="group" class="ms-4">Group</label>
                            <select name="group" class="form-control" value={{ $role->group }}>
                                <option value="system">System</option>
                                <option value="user">User</option>
        
                            </select>
        
                            @error('group')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>

                        <div class="row form-group">
                            <label for="Permission">Permission</label>
                            @foreach ($permissions as $groupName => $permission)
                            <div class="col-lg-4">
                                <label for="">{{ $groupName }}</label>
                                <div form-group>
                                    @foreach ($permission as $item)
                                    <div class="form-check"> 
                                            <input 
                                            type="checkbox" class="form-check-input" name="permission_ids_{{$item->id}}" {{ $role->permissions->contains('name', $item->name) ? 'checked' : '' }} value="{{ $item->id }}">
                                            <label class="custom-control-label" for="">{{ $item->display_name }}</label>
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection