routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\OrderController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Client\CartController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/product', [HomeController::class, 'products'])->name('productlist');

Route::get('/index', function () {
    return view('client.layout.app');
});

Route::get('/blog', function () {
    return view('client.blog.blog');
})->name('blog');

Route::get('/myaccount', function () {
    return view('client.myaccount.dashboard');
})->name('myaccount');

Route::get('/client_account', function () {
    return view('client.myaccount.account');
})->name('myaccount');

Route::get('/client_address', function () {
    return view('client.myaccount.addresses');
})->name('myaccount');

Route::get('/client_wishlist', function () {
    return view('client.myaccount.wishlist');
})->name('myaccount');

Route::get('/client_orders', function () {
    return view('client.myaccount.orders');
})->name('myaccount');

Route::get('/about', function () {
    return view('client.about.about');
})->name('about');

Route::get('/contact', function () {
    return view('client.contact.contact');
})->name('contact');

Route::get('/productdetail', function () {
    return view('client.product.productdetail');
})->name('productdetail');

Route::get('/myaccount/orders', [MyAccountController::class, 'orders'])->name('myaccount.orders');

Route::prefix('admin')->group(function () {
    Route::get('/categories', [CategoryController::class, 'index'])->name('admin.categories.index');
    Route::get('/categories/create', [CategoryController::class, 'create'])->name('admin.categories.create');
    Route::post('/categories', [CategoryController::class, 'store'])->name('admin.categories.store');
});

Route::get('product/{category_id}', [ClientProductController::class, 'index']) -> name('client.product.productlist');

Route::get('productdetail/{id}', [ClientProductController::class, 'show']) -> name('client.product.productdetail');


//admin route
Route::middleware('auth')->group(function(){
 
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard');

    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('products', ProductController::class);
    Route::resource('coupon', CouponController::class);
    Route::post('/admin/products', [AdminController::class, 'products'])->name('admin.products');

});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/search', [ClientProductController::class, 'search'])->name('client.product.search');

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class, 'store']) -> name('client.cart.add');
    Route::get('cart', [CartController::class, 'index']) -> name('client.cart.cart');
    Route::post('update-quantity-product-in-cart/{cart_product_id}', [CartController::class, 'updateQuantityProduct'])->name('client.cart.update_product_quantity');

    Route::post('apply-coupon', [CartController::class, 'applyCoupon']) ->name('client.cart.apply_coupon');
    Route::get('checkout', [CartController::class, 'checkout']) -> name('client.checkout.index')->middleware('user.can_checkout_cart');
    Route::post('process-checkout', [CartController::class, 'processCheckout'])->name('client.checkout.proccess')->middleware('user.can_checkout_cart');

});

app/Models/Coupon.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Coupon extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'type', 'value', 'expiry_date'
    ];

    public function getExpiryDateAttribute()
    {
        return Carbon::parse($this->attributes['expiry_date'])->format('Y-m-d');
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'coupon_user');
    }

    public function firtWithExpiryDate($name, $userId)
    {
        return $this->whereName($name)->whereDoesntHave('users', fn($q) => $q->where('users.id', $userId))
        ->whereDate('expiry_date', '>=', Carbon::now())->first();
    }


}

app/Http/Controllers/Admin/CouponController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Coupons\CreateCouponRequest;
use App\Http\Requests\Coupons\UpdateCouponRequest;
use Illuminate\Http\Request;
use App\Models\Coupon;
use Carbon\Carbon;



class CouponController extends Controller
{
    protected $coupon;
     public function __construct(Coupon $coupon)
    {
        $this -> coupon = $coupon;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coupons = $this->coupon->latest('id')->paginate(5);

        return view('admin.coupon.index', compact('coupons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.coupon.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCouponRequest $request)
    {
        $dataCreate =  $request->all();

        $this->coupon->create($dataCreate);


        return redirect()->route('coupon.index')->with(['message' => 'Create coupon success']);
    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $coupon = $this->coupon->findOrFail($id);

        return view('admin.coupon.edit', compact('coupon'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $coupon = $this->coupon->findOrFail($id);

        $dataUpdate = $request->all();
        $coupon->update($dataUpdate);

        return redirect()->route('coupon.index')->with(['message' => 'Update coupon success']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

            $coupon = $this->coupon->findOrFail($id);
            $coupon->delete();
    
            return redirect()->route('coupon.index')->with(['message' => 'Delete '.$coupon->name.' success']);
    
    }
}

resources/views/admin/coupon/create.blade.php
@extends('admin.layout.app')
@section('title', 'Create Coupon')
@section('content')
    <div class="card">
        @if(session()->has("error"))
            <p>{{session()->get("error")}}</p>
        @endif
        <h1>Create Coupon</h1>
        
        <div>
            <form action="{{ route('coupon.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="modal-body px-4">
                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" style="text-transform: uppercase" name="name" value="{{ old('name') }}">
                            </div>
                            @error('name')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>       

                        <div class="col-lg-6">
                        <label name="group" class="ms-4">Type</label>
                        <select name="type" class="form-control">
                            <option>Select Type</option>
                            <option value="money">Money</option>
                        </select>
                        @error('type')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>      

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Value</label>
                                <input type="number" class="form-control" name="value" value="{{ old('value') }}">
                            </div>
                            @error('value')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div> 

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Expiry Date</label>
                                <input type="date" class="form-control" name="expiry_date" value="{{ old('expiry_date') }}">
                            </div>
                            @error('expiry_date')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div> 

                    </div>
                </div>
                

                <div class="modal-footer px-4">
                    <a href="{{ route('coupon.index')}}"><button type="button" class="btn btn-secondary btn-pill">Cancel</button></a>
                    <button type="submit" class="btn btn-submit btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        const onSelectImage = e=>{
            const n = e.target.value.split("\\").length;
            document.querySelector("#img_name_label").innerText = e.target.value.split("\\")[n-1];
        }
    </script>
@endsection

resources/views/admin/coupon/edit.blade.php
@extends('admin.layout.app')
@section('title', 'Edit Coupon ' . $coupon->name)
@section('content')
<div class="card">
    @if(session()->has("error"))
        <p>{{session()->get("error")}}</p>
    @endif
    <h1>Edit Coupon</h1>
    
    <div>
            <form action="{{ route('coupon.update', $coupon->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="modal-body px-4">
                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" style="text-transform: uppercase" name="name" value="{{ old('name') ?? $coupon->name }}">
                            </div>
                            @error('name')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>       

                        <div class="col-lg-6">
                        <label name="group" class="ms-4">Type</label>
                        <select name="type" class="form-control">
                            <option>Select Type</option>
                            <option value="money" {{ old('type') ?? $coupon->type == 'money' ? 'selected' : '' }}>Money</option>
                        </select>
                        @error('type')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>      

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Value</label>
                                <input type="number" class="form-control" name="value" value="{{ old('value') ?? $coupon->value  }}">
                            </div>
                            @error('value')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div> 

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Expiry Date</label>
                                <input type="date" class="form-control" name="expiry_date" value="{{ old('expiry_date') ?? $coupon->expiry_date }}">
                            </div>
                            @error('expiry_date')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div> 

                    </div>
                </div>
                

                <div class="modal-footer px-4">
                    <a href="{{ route('coupon.index')}}"><button type="button" class="btn btn-secondary btn-pill">Cancel</button></a>
                    <button type="submit" class="btn btn-submit btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        const onSelectImage = e=>{
            const n = e.target.value.split("\\").length;
            document.querySelector("#img_name_label").innerText = e.target.value.split("\\")[n-1];
        }
    </script>
@endsection