routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\OrderController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Client\CartController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/product', [HomeController::class, 'products'])->name('productlist');

Route::get('/index', function () {
    return view('client.layout.app');
});

Route::get('/blog', function () {
    return view('client.blog.blog');
})->name('blog');

Route::get('/myaccount', function () {
    return view('client.myaccount.dashboard');
})->name('myaccount');

Route::get('/client_account', function () {
    return view('client.myaccount.account');
})->name('myaccount');

Route::get('/client_address', function () {
    return view('client.myaccount.addresses');
})->name('myaccount');

Route::get('/client_wishlist', function () {
    return view('client.myaccount.wishlist');
})->name('myaccount');

Route::get('/client_orders', function () {
    return view('client.myaccount.orders');
})->name('myaccount');

Route::get('/about', function () {
    return view('client.about.about');
})->name('about');

Route::get('/contact', function () {
    return view('client.contact.contact');
})->name('contact');

Route::get('/productdetail', function () {
    return view('client.product.productdetail');
})->name('productdetail');

Route::get('/myaccount/orders', [MyAccountController::class, 'orders'])->name('myaccount.orders');

Route::prefix('admin')->group(function () {
    Route::get('/categories', [CategoryController::class, 'index'])->name('admin.categories.index');
    Route::get('/categories/create', [CategoryController::class, 'create'])->name('admin.categories.create');
    Route::post('/categories', [CategoryController::class, 'store'])->name('admin.categories.store');
});

Route::get('product/{category_id}', [ClientProductController::class, 'index']) -> name('client.product.productlist');

Route::get('productdetail/{id}', [ClientProductController::class, 'show']) -> name('client.product.productdetail');


//admin route
Route::middleware('auth')->group(function(){
 
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard');

    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('products', ProductController::class);
    Route::resource('coupon', CouponController::class);
    Route::post('/admin/products', [AdminController::class, 'products'])->name('admin.products');

});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/search', [ClientProductController::class, 'search'])->name('client.product.search');

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class, 'store']) -> name('client.cart.add');
    Route::get('cart', [CartController::class, 'index']) -> name('client.cart.cart');
    Route::post('update-quantity-product-in-cart/{cart_product_id}', [CartController::class, 'updateQuantityProduct'])->name('client.cart.update_product_quantity');

    Route::post('apply-coupon', [CartController::class, 'applyCoupon']) ->name('client.cart.apply_coupon');
    Route::get('checkout', [CartController::class, 'checkout']) -> name('client.checkout.index')->middleware('user.can_checkout_cart');
    Route::post('process-checkout', [CartController::class, 'processCheckout'])->name('client.checkout.proccess')->middleware('user.can_checkout_cart');

});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles;

    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'address',
        'gender',
        'img',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function role(){
        return $this->belongsTo(Role::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Role;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    protected $user;
    protected $role;

    public function __construct(User $user, Role $role)
    {
        $this->user = $user;

        $this->role = $role;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = $this->user->latest('id')->paginate(10);
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $roles = Role::all()->groupBy('group_name');
        return view('admin.user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $dataCreate = $request->all();
        // $dataCreate['password'] = Hash::make($request->password);
        // verify that email and phone number are in use
        $user = User::where("email", $request->email)->first();
        if($user) return to_route('users.create')->with(['error' =>'email in use']);
        $user = User::where("phone", $request->phone)->first();
        if($user) return to_route('users.create')->with(['error' =>'phone in use']);
        User::create(array_merge($request->all(),["img"=>self::uploadImage($request,"users"),
        "password"=>Hash::make($request->password)]));
        return to_route('users.index')->with(['message' =>'create success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = $this->user->findOrFail($id);
        $roles = Role::all()->groupBy("group");
        return view('admin.user.edit', compact('user', "roles"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user = User::find($id);
        if (!$user) {
            return to_route('users.edit', $id)->with(['error' => 'User not found']);
        }
        $dataUpdate = $request->all();

        // If a new password is provided, hash it
        if ($request->password) {
            $dataUpdate['password'] = Hash::make($request->password);
        } else {
            // Remove password from the data if not provided
            unset($dataUpdate['password']);
        }

        // If a new image is uploaded, handle the image upload
        if ($request->hasFile('img')) {
            $dataUpdate['img'] = self::uploadImage($request, "users");
        } else {
            // Keep the old image if no new image is provided
            unset($dataUpdate['img']);
        }

        // Update the user
        $user->update($dataUpdate);

        return to_route('users.index')->with(['message' => 'Update success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::find($id);
        if (!$user) {
            return to_route('users.index')->with(['error' => 'User not found']);
        }

        // Delete the user image if it exists
        if ($user->img) {
            $imagePath = public_path($user->img);
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }
        }

        // Delete the user
        $user->delete();

        return to_route('users.index')->with(['message' => 'User deleted successfully']);
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layout.app')
@section('title', 'Create Users')
@section('content')
    <div class="card">
        @if(session()->has("error"))
            <p>{{session()->get("error")}}</p>
        @endif
        <h1>Create User</h1>
        
        <div>
            <form action="{{ route('users.store') }}" method="post" enctype="multipart/form-data">
                @csrf

                <div class="modal-body px-4">
                    <div class="form-group row mb-6">
                        <label for="img" class="col-sm-4 col-lg-2 col-form-label">User
                            Image</label>

                        <div class="col-sm-8 col-lg-10">
                            <div class="custom-file mb-1">
                                <input type="file" class="custom-file-input" name="img" id="img"  onchange="onSelectImage(event)">
                                <label class="custom-file-label" for="img" id="img_name_label">Choose
                                    file...</label>
                                <div class="invalid-feedback">Example invalid custom file feedback
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                            </div>
                            @error('name')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" name="email" value="{{ old('email') }}">
                            </div>
                            @error('email')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group mb-4">
                                <label>Password</label>
                                <input type="password" class="form-control" name="password">
                            </div>
                            @error('password')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <label name="group" class="ms-4">Gender</label>
                            <select name="gender" class="form-control">
                                <option value="Male">Male</option>
                                <option value="Fe-male">FeMale</option>                    
                            </select>
        
                            @error('gender')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group mb-4">
                                <label>Phone</label>
                                <input type="text" class="form-control" name="phone" value="{{ old('phone') }}">
                            </div>
                            @error('phone')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group mb-4">
                                <label>Address</label>
                                <textarea name="address" class="form-control">{{ old('address') }} </textarea>
                            </div>
                            @error('address')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror                
                        </div>
                        <div class="row form-group">
                            <label for="roleSelect">Roles</label>
                            <div class="col-lg-12">
                                <select id="roleSelect" name="role_id" class="form-control">
                                    @foreach ($roles as $groupName => $role)
                                        <optgroup label="{{ $groupName }}">
                                            @foreach ($role as $irole)
                                                <option value="{{ $irole->id }}">{{ $irole->display_name }}</option>
                                            @endforeach
                                        </optgroup>
                                    @endforeach
                                </select>
                            </div>
                        </div>                        
                    </div>
                </div>
                

                <div class="modal-footer px-4">
                    <a href="{{ route('users.index')}}"><button type="button" class="btn btn-secondary btn-pill">Cancel</button></a>
                    <button type="Submit" class="btn btn-submit btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        const onSelectImage = e=>{
            const n = e.target.value.split("\\").length;
            document.querySelector("#img_name_label").innerText = e.target.value.split("\\")[n-1];
        }
    </script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layout.app')
@section('title', 'Edit Users ' . $user->name)
@section('content')
    <div class="card">
        
        <h1>Edit User</h1>

        <div>
            <form action="{{ route('users.update', $user->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')


                <div class="modal-body px-4">
                    <div class="form-group row mb-6">
                        <label for="img" class="col-sm-4 col-lg-2 col-form-label">User
                            Image</label>

                        <div class="col-sm-8 col-lg-10">
                            <div id="current-img-container" class="mb-3">
                                <img id="current-img" src="{{ asset($user->img) }}" alt="Current User Image" class="img-thumbnail" style="max-width: 150px;">
                            </div>
                            <div class="custom-file mb-1">
                                <input type="file" class="custom-file-input" name="img" id="img"  onchange="onSelectImage(event)">
                                <label class="custom-file-label" for="img" id="img_name_label">Choose
                                    file...</label>
                                <div class="invalid-feedback">Example invalid custom file feedback
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" name="name" value="{{ old('name') ?? $user->name }}">
                            </div>
                            @error('name')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" name="email" value="{{ old('email')?? $user->email }}">
                            </div>
                            @error('email')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group mb-4">
                                <label>Password</label>
                                <input type="password" class="form-control" name="password">
                            </div>
                            @error('password')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <label name="group" class="ms-4">Gender</label>
                            <select name="gender" class="form-control" value={{ $user->gender}}>
                                <option value="male">Male</option>
                                <option value="fe-male">FeMale</option>                    
                            </select>
        
                            @error('gender')
                                <span class="text-danger"> {{ $message }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group mb-4">
                                <label>Phone</label>
                                <input type="text" class="form-control" name="phone" value="{{ old('phone') ?? $user->phone }}">
                            </div>
                            @error('phone')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group mb-4">
                                <label>Address</label>
                                <textarea name="address" class="form-control">{{ old('address') ?? $user->address }}</textarea>
                            </div>
                            @error('address')
                                <span class="text-danger"> {{ $error }}</span>
                            @enderror                
                        </div>
                        <div class="row form-group">
                            <label for="role_id" class="col-lg-2 col-form-label">Roles</label>
                            <div class="col-lg-10">
                                <select class="form-control" name="role_id" id="role_id">
                                    @foreach ($roles as $groupName => $roleGroup)
                                        <optgroup label="{{ $groupName }}">
                                            @foreach ($roleGroup as $irole)
                                                <option value="{{ $irole->id }}" {{ $irole->id === $user->role->id ? 'selected' : '' }}>
                                                    {{ $irole->display_name }}
                                                </option>
                                            @endforeach
                                        </optgroup>
                                    @endforeach
                                </select>
                            </div>
                        </div>                        
                    </div>
                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <script>
        const onSelectImage = e=>{
            const n = e.target.value.split("\\").length;
            document.querySelector("#img_name_label").innerText = e.target.value.split("\\")[n-1];
        }
    </script>
@endsection